### ISSUE TITLE
CreateAssetMenuAttribute

### ISSUE THREAD

**Issue by korchoon** [zsaladin/ScriptableObjectCreator#1]
Hi. Sorry for unwanted suggestion. But you (and others that will find your snippet) could simply use [CreateAssetMenu] attribute on class inherited from ScriptableObject
https://docs.unity3d.com/ScriptReference/CreateAssetMenuAttribute.html

**Comment by zsaladin** [comment]
Honestly I didn't know the attribute [CreateAssetMenu] when I created this repository. As you can see, this repository isn't maintained because it's useless due to [CreateAssetMenu]. Haha

But anyway thank you for letting me know.
